// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAO2DzRW8jQGNBDtBMxOy87RmbtFarmMw',
    appId: '1:435072647861:web:d78b34ddd0c53f212af4fc',
    messagingSenderId: '435072647861',
    projectId: 'clothing-ecommerce-app-18b40',
    authDomain: 'clothing-ecommerce-app-18b40.firebaseapp.com',
    storageBucket: 'clothing-ecommerce-app-18b40.firebasestorage.app',
    measurementId: 'G-RJZ7W2T3RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqqMenqGHr-cdIOPVD-YXxwTlria2jvhs',
    appId: '1:435072647861:android:744a158fee0f93382af4fc',
    messagingSenderId: '435072647861',
    projectId: 'clothing-ecommerce-app-18b40',
    storageBucket: 'clothing-ecommerce-app-18b40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB138ZVrssT8CWXul-P_-hqF-2cNaxnwqU',
    appId: '1:435072647861:ios:8942aa0ea818f9512af4fc',
    messagingSenderId: '435072647861',
    projectId: 'clothing-ecommerce-app-18b40',
    storageBucket: 'clothing-ecommerce-app-18b40.firebasestorage.app',
    iosBundleId: 'com.example.clothingEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB138ZVrssT8CWXul-P_-hqF-2cNaxnwqU',
    appId: '1:435072647861:ios:8942aa0ea818f9512af4fc',
    messagingSenderId: '435072647861',
    projectId: 'clothing-ecommerce-app-18b40',
    storageBucket: 'clothing-ecommerce-app-18b40.firebasestorage.app',
    iosBundleId: 'com.example.clothingEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAO2DzRW8jQGNBDtBMxOy87RmbtFarmMw',
    appId: '1:435072647861:web:f797e5533188cae92af4fc',
    messagingSenderId: '435072647861',
    projectId: 'clothing-ecommerce-app-18b40',
    authDomain: 'clothing-ecommerce-app-18b40.firebaseapp.com',
    storageBucket: 'clothing-ecommerce-app-18b40.firebasestorage.app',
    measurementId: 'G-PEK1NV0FP0',
  );
}
